/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package largeFileGeneration;

import com.beanit.jasn1.ber.BerLength;
import com.beanit.jasn1.ber.BerTag;
import com.beanit.jasn1.ber.ReverseByteArrayOutputStream;
import com.beanit.jasn1.ber.types.BerBoolean;
import com.beanit.jasn1.ber.types.BerInteger;
import com.beanit.jasn1.ber.types.BerType;
import com.beanit.jasn1.ber.types.string.BerUTF8String;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;


public class GenericCallDataRecord implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private BerUTF8String firstName = null;
	private BerUTF8String lastName = null;
	private BerInteger recordNumber = null;
	private BerInteger age = null;
	private BerBoolean isVIP = null;
	private BerUTF8String city = null;
	private BerUTF8String country = null;
	private BerUTF8String callingNumber = null;
	private BerUTF8String calledNumber = null;
	private BerUTF8String zipCode = null;
	private BerUTF8String longitude = null;
	private BerUTF8String latitude = null;
	private BerUTF8String startDate = null;
	private BerUTF8String startTime = null;
	private BerInteger duration = null;
	
	public GenericCallDataRecord() {
	}

	public GenericCallDataRecord(byte[] code) {
		this.code = code;
	}

	public void setFirstName(BerUTF8String firstName) {
		this.firstName = firstName;
	}

	public BerUTF8String getFirstName() {
		return firstName;
	}

	public void setLastName(BerUTF8String lastName) {
		this.lastName = lastName;
	}

	public BerUTF8String getLastName() {
		return lastName;
	}

	public void setRecordNumber(BerInteger recordNumber) {
		this.recordNumber = recordNumber;
	}

	public BerInteger getRecordNumber() {
		return recordNumber;
	}

	public void setAge(BerInteger age) {
		this.age = age;
	}

	public BerInteger getAge() {
		return age;
	}

	public void setIsVIP(BerBoolean isVIP) {
		this.isVIP = isVIP;
	}

	public BerBoolean getIsVIP() {
		return isVIP;
	}

	public void setCity(BerUTF8String city) {
		this.city = city;
	}

	public BerUTF8String getCity() {
		return city;
	}

	public void setCountry(BerUTF8String country) {
		this.country = country;
	}

	public BerUTF8String getCountry() {
		return country;
	}

	public void setCallingNumber(BerUTF8String callingNumber) {
		this.callingNumber = callingNumber;
	}

	public BerUTF8String getCallingNumber() {
		return callingNumber;
	}

	public void setCalledNumber(BerUTF8String calledNumber) {
		this.calledNumber = calledNumber;
	}

	public BerUTF8String getCalledNumber() {
		return calledNumber;
	}

	public void setZipCode(BerUTF8String zipCode) {
		this.zipCode = zipCode;
	}

	public BerUTF8String getZipCode() {
		return zipCode;
	}

	public void setLongitude(BerUTF8String longitude) {
		this.longitude = longitude;
	}

	public BerUTF8String getLongitude() {
		return longitude;
	}

	public void setLatitude(BerUTF8String latitude) {
		this.latitude = latitude;
	}

	public BerUTF8String getLatitude() {
		return latitude;
	}

	public void setStartDate(BerUTF8String startDate) {
		this.startDate = startDate;
	}

	public BerUTF8String getStartDate() {
		return startDate;
	}

	public void setStartTime(BerUTF8String startTime) {
		this.startTime = startTime;
	}

	public BerUTF8String getStartTime() {
		return startTime;
	}

	public void setDuration(BerInteger duration) {
		this.duration = duration;
	}

	public BerInteger getDuration() {
		return duration;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		codeLength += duration.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 19
		reverseOS.write(0x53);
		codeLength += 1;
		
		codeLength += startTime.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 18
		reverseOS.write(0x52);
		codeLength += 1;
		
		codeLength += startDate.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 16
		reverseOS.write(0x50);
		codeLength += 1;
		
		codeLength += latitude.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 12
		reverseOS.write(0x4C);
		codeLength += 1;
		
		codeLength += longitude.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 11
		reverseOS.write(0x4B);
		codeLength += 1;
		
		codeLength += zipCode.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 10
		reverseOS.write(0x4A);
		codeLength += 1;
		
		codeLength += calledNumber.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 9
		reverseOS.write(0x49);
		codeLength += 1;
		
		codeLength += callingNumber.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 8
		reverseOS.write(0x48);
		codeLength += 1;
		
		codeLength += country.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 7
		reverseOS.write(0x47);
		codeLength += 1;
		
		codeLength += city.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 6
		reverseOS.write(0x46);
		codeLength += 1;
		
		codeLength += isVIP.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 5
		reverseOS.write(0x45);
		codeLength += 1;
		
		codeLength += age.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 4
		reverseOS.write(0x44);
		codeLength += 1;
		
		codeLength += recordNumber.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 3
		reverseOS.write(0x43);
		codeLength += 1;
		
		codeLength += lastName.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 2
		reverseOS.write(0x42);
		codeLength += 1;
		
		codeLength += firstName.encode(reverseOS, false);
		// write tag: APPLICATION_CLASS, PRIMITIVE, 1
		reverseOS.write(0x41);
		codeLength += 1;
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 1)) {
			firstName = new BerUTF8String();
			subCodeLength += firstName.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 2)) {
			lastName = new BerUTF8String();
			subCodeLength += lastName.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 3)) {
			recordNumber = new BerInteger();
			subCodeLength += recordNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 4)) {
			age = new BerInteger();
			subCodeLength += age.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 5)) {
			isVIP = new BerBoolean();
			subCodeLength += isVIP.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 6)) {
			city = new BerUTF8String();
			subCodeLength += city.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 7)) {
			country = new BerUTF8String();
			subCodeLength += country.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 8)) {
			callingNumber = new BerUTF8String();
			subCodeLength += callingNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 9)) {
			calledNumber = new BerUTF8String();
			subCodeLength += calledNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 10)) {
			zipCode = new BerUTF8String();
			subCodeLength += zipCode.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 11)) {
			longitude = new BerUTF8String();
			subCodeLength += longitude.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 12)) {
			latitude = new BerUTF8String();
			subCodeLength += latitude.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 16)) {
			startDate = new BerUTF8String();
			subCodeLength += startDate.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 18)) {
			startTime = new BerUTF8String();
			subCodeLength += startTime.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.APPLICATION_CLASS, BerTag.PRIMITIVE, 19)) {
			duration = new BerInteger();
			subCodeLength += duration.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (firstName != null) {
			sb.append("firstName: ").append(firstName);
		}
		else {
			sb.append("firstName: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (lastName != null) {
			sb.append("lastName: ").append(lastName);
		}
		else {
			sb.append("lastName: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (recordNumber != null) {
			sb.append("recordNumber: ").append(recordNumber);
		}
		else {
			sb.append("recordNumber: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (age != null) {
			sb.append("age: ").append(age);
		}
		else {
			sb.append("age: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (isVIP != null) {
			sb.append("isVIP: ").append(isVIP);
		}
		else {
			sb.append("isVIP: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (city != null) {
			sb.append("city: ").append(city);
		}
		else {
			sb.append("city: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (country != null) {
			sb.append("country: ").append(country);
		}
		else {
			sb.append("country: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (callingNumber != null) {
			sb.append("callingNumber: ").append(callingNumber);
		}
		else {
			sb.append("callingNumber: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (calledNumber != null) {
			sb.append("calledNumber: ").append(calledNumber);
		}
		else {
			sb.append("calledNumber: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (zipCode != null) {
			sb.append("zipCode: ").append(zipCode);
		}
		else {
			sb.append("zipCode: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (longitude != null) {
			sb.append("longitude: ").append(longitude);
		}
		else {
			sb.append("longitude: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (latitude != null) {
			sb.append("latitude: ").append(latitude);
		}
		else {
			sb.append("latitude: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (startDate != null) {
			sb.append("startDate: ").append(startDate);
		}
		else {
			sb.append("startDate: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (startTime != null) {
			sb.append("startTime: ").append(startTime);
		}
		else {
			sb.append("startTime: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (duration != null) {
			sb.append("duration: ").append(duration);
		}
		else {
			sb.append("duration: <empty-required-field>");
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

